### ISSUE TITLE
Make placeholders smoother

### ISSUE THREAD

**Issue by ghost** [johannschopplich/kirby-blurry-placeholder#24]
Hey there,

when using your plugin "as-is", I get this:

<img width="1136" alt="Screenshot 2023-03-25 at 19 24 40" src="https://user-images.githubusercontent.com/122524301/227734990-f5dec7cb-dbd1-46ff-9b41-6630ec36a8dd.png">

From the banner image, I was under the impression to get softer gradients and overall smoother images, is there a way to "improve" the output quality by tweaking parameters? Or is it my images (strong light/shadow transitions etc)

Thanks!

**Comment by ghost** [comment]
// Edit:

For PNG files with transparency, I get this:

<img width="1336" alt="Screenshot 2023-03-26 at 09 04 44" src="https://user-images.githubusercontent.com/122524301/227760790-1217b245-9db6-4f07-9dd0-7b18c3d8d4c6.png">

**Comment by johannschopplich** [comment]
Hello there!

You can try to improve the [pixel target](https://github.com/johannschopplich/kirby-blurry-placeholder#global) to generate bigger thumbnails (although not recommended), which are embedded into the blurry SVG placeholder. The implementation mocks the one from Google's former AMP project. I'm not sure what you expected. In my opinion, your placeholders are smooth. Every image is different. So yeah, maybe it's the color contrast.

Regarding transparent images, there is the [`transparent` option](https://github.com/johannschopplich/kirby-blurry-placeholder#file-methods) for both `$file->placeholder()` and `$file->placeholderUri()` field methods. It will omit the artifacts of transparent images.

There is also a different implementation for blurry images using the `blurhash` algorithm by @tobimori which you might prefer, since more details is preserved. You can check it out as well: [kirby-blurhash](https://github.com/tobimori/kirby-blurhash)

**Comment by tobimori** [comment]
You can customize the blur by adjusting the stdDeviation in https://github.com/johannschopplich/kirby-blurry-placeholder/blob/main/BlurryPlaceholder.php#L54

**Comment by johannschopplich** [comment]
@tobimori Great input! 👏

**Comment by ghost** [comment]
Thanks you guys! Seems even @johannschopplich learned something 😅 (just kidding)

**Comment by johannschopplich** [comment]
Absolutely! The younger generation builds upon what the older one has created and teaches a lesson or two. Circle of life. 🙃

The Gaussian blur parameter could be a plugin option. 👀

**Comment by ghost** [comment]
Not sure about who's the younger generation here 🤣 

That's what I ended up with (note the blur in the beginning, the bw-color effect applies to all images, see the end of the clip, when scrolling up again)

https://user-images.githubusercontent.com/122524301/227766297-d3019370-f559-4a0e-b83e-869a7875888c.mov

**Comment by ghost** [comment]
The filesize savings are quite decent, and in accordance with the bw effect, with placeholders being generated as bw, this shaves some additional kb 😉

**Comment by ghost** [comment]
> Absolutely! The younger generation builds upon what the older one has created and teaches a lesson or two. Circle of life. 🙃
> 
> The Gaussian blur parameter could be a plugin option. 👀

TOTALLY!
