### ISSUE TITLE
Placeholder from external image

### ISSUE THREAD

**Issue by Thiousi** [johannschopplich/kirby-blurry-placeholder#27]
Some of the images on my site are external. I have product pages which have url references to images on shopify cdn. Is there any chance to make this work with external images? Or should I somehow try to generate thumbs in place?

**Comment by johannschopplich** [comment]
You could try to fetch the image in Kirby and save it to a custom content folder. On these images you can then run call the blurry placeholder methods. 

Every image supported by this plugin has to originate from Kirby because of the thumbnail logic provided. 

Closing this, as it is out of scope for this plugin. Good luck finding a solution!

Edit: You can try to use blurhash or thumbhash placeholders. Maybe these are supported by Shopify. 
Use them with my [unlazy](https://unlazy.byjohann.dev) library.
